apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ template "postgresql.fullname" . }}
spec:
  version: "11.2"
  storageType: Durable
  storage:
    storageClassName: "do-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate